osx_image: xcode8
language: objective-c

script:
- set -o pipefail && xcodebuild test -project SpeedLog.xcodeproj -scheme SpeedLog -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick

notifications:
  email:
    on_success: never
    on_failure: change
